name: E2E

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, labeled]

permissions:
  contents: read
  packages: write

jobs:
  build-gateway:
    if: github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'e2e')
    uses: ./.github/workflows/docker-build.yml
    with:
      component: gateway
      platform: linux/arm64
      runner: build-arm64

  build-cluster:
    if: github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'e2e')
    uses: ./.github/workflows/docker-build.yml
    with:
      component: cluster
      platform: linux/arm64
      runner: build-arm64

  e2e:
    needs: [build-gateway, build-cluster]
    uses: ./.github/workflows/e2e-test.yml
    with:
      image-tag: ${{ github.sha }}
      runner: build-arm64
